# Generated by Django 4.1.3 on 2023-01-15 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option_text', models.TextField(verbose_name='Texto de la respuesta')),
                ('is_correct', models.BooleanField(verbose_name='Correcta')),
            ],
            options={
                'verbose_name': 'answer_option',
                'verbose_name_plural': 'answer_options',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre del juego')),
                ('expected_start_time', models.DateTimeField(verbose_name='Fecha esperada de inicio')),
                ('real_start_time', models.DateTimeField(blank=True, verbose_name='Fecha real de inicio')),
                ('finished_time', models.DateTimeField(blank=True, verbose_name='Fecha de finalización')),
                ('is_active', models.BooleanField(default=False, verbose_name='Juego activo')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de voto')),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.answer_option', verbose_name='Answer_option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texto de la pregunta')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.AddField(
            model_name='answer_option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.question', verbose_name='Question'),
        ),
    ]
